import "./globals.css";

export const metadata = {
  title: "Landing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`  font-manrope antialiased`}>{children}</body>
    </html>
  );
}
